services:
  - type: web
    name: diagonale
    env: node
    plan: free
    buildCommand: npm install && node build-render.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false